// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfyrazbbicptngrailgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmeXJhemJiaWNwdG5ncmFpbGdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTg2MTcsImV4cCI6MjA2NjUzNDYxN30.bbdmHvsUkXJT9_7xjfq__UUbIwlbeAP4tsgA9_DaTJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);